training:
  batch_size: 16
  learning_rate: 0.0005
  epoch_num: 35
  momentum: 0.9
  image_size: 96,96

# all path starts from project root.
data:
  dataset_path1: data/mask/dataset1
  dataset_path2: data/mask/dataset2
  dataset_path3: data/mask/dataset3
  dataset_path4: data/mask/dataset4
  class_num: 2

# images and xml labels to change into yolo train format
face_data:
  path: data/face/labeled_image



yolo_training:
  batch_size: 128
  learning_rate: 0.001
  epoch_num: 80
  momentum: 0.9
  image_size: 64,64
  data:
    dataset_path: data/face
    yolo_format_export_path: data/yolo